### ISSUE TITLE
downsample f'{path} not found'

### ISSUE THREAD

**Issue by gptomaleri** [ml-struct-bio/cryodrgn#104]
Hi, 

I am running into issues when I am running cryodrgn downsample for my .cs file. 

Traceback (most recent call last):
  File "/programs/x86_64-linux//cryodrgn/0.3.2/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.2', 'console_scripts', 'cryodrgn')())
  File "/programs/x86_64-linux/cryodrgn/0.3.2/cryodrgn_extlib/miniconda3-4.9.2_py37-rpp3/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/__main__.py", line 52, in main
    args.func(args)
  File "/programs/x86_64-linux/cryodrgn/0.3.2/cryodrgn_extlib/miniconda3-4.9.2_py37-rpp3/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/commands/downsample.py", line 40, in main
    old = dataset.load_particles(args.mrcs, lazy=True, datadir=args.datadir, relion31=args.relion31)
  File "/programs/x86_64-linux/cryodrgn/0.3.2/cryodrgn_extlib/miniconda3-4.9.2_py37-rpp3/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/dataset.py", line 32, in load_particles
    particles = starfile.csparc_get_particles(mrcs_txt_star, datadir, lazy)
  File "/programs/x86_64-linux/cryodrgn/0.3.2/cryodrgn_extlib/miniconda3-4.9.2_py37-rpp3/lib/python3.7/site-packages/cryodrgn-0.3.2-py3.7.egg/cryodrgn/starfile.py", line 121, in csparc_get_particles
    assert os.path.exists(path), f'{path} not found'
AssertionError: "deleted name and path" not found 

I am not sure why

**Comment by zhonge** [comment]
The `.cs` file is a metadata file that points to the location of `.mrc`/`.mrcs` files. Sometimes the paths can be broken if you've been moving the dataset between machines/filesystems. Does the path to the `.mrcs` file specified in the AssertionError exist? 

You can also use the `--datadir` flag to overwrite the directory to the particles, though, this will only work if all the particles are in the same directory.

**Comment by gptomaleri** [comment]
Hi Zhonge, Thanks for getting back so quickly. Indeed --datadir worked just fine.

Now I am running into problems trying to start the training with my dataset. Not sure if this is because I am running it at a cluster...

central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/bin/cryodrgn train_vae particles.200.mrcs --poses poses.pkl --ctf ctf.pkl --zdim 8 -n 50 -o 00_vae168
2022-01-31 16:33:13     Namespace(activation='relu', amp=False, batch_size=8, beta=None, beta_control=None, checkpoint=1, ctf='/central/groups/voorheeslab/gpintont/software/cryoDRGN /P23_J124/ctf.pkl', datadir=None, do_pose_sgd=False, domain='fourier', emb_type='quat', enc_mask=None, encode_mode='resid', func=<function main at 0x7f7bfa95f950>, ind=None, invert_data=True, lazy=False, load=None, log_interval=1000, lr=0.0001, max_threads=16, multigpu=False, norm=None, num_epochs=50, outdir='/central/groups/voorheeslab/gpintont/software /cryoDRGN/P23_J124/00_vae168', particles='/central/groups/voorheeslab/gpintont/software /cryoDRGN/P23_J124/particles.200.mrcs', pdim=256, pe_dim=None, pe_type='geom_lowf', players=3, pose_lr=0.0003, poses='/central/groups/voorheeslab/gpintont/software /cryoDRGN/P23_J124/poses.pkl', preprocessed=False, pretrain=1, qdim=256, qlayers=3, relion31=False, seed=23124, tilt=None, tilt_deg=45, use_real=False, verbose=False, wd=0, window=True, window_r=0.85, zdim=8)
2022-01-31 16:33:13     Use cuda False
2022-01-31 16:33:13     WARNING: No GPUs detected
2022-01-31 16:33:13     Loading dataset from /central/groups/voorheeslab/gpintont/software/cryoDRGN/P23_J124/particles.200.mrcs
Traceback (most recent call last):
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.4', 'console_scripts', 'cryodrgn')())
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/__main__.py", line 54, in main
    args.func(args)
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/commands/train_vae.py", line 319, in main
    data = dataset.MRCData(args.particles, norm=args.norm, invert_data=args.invert_data, ind=ind, keepreal=args.use_real, window=args.window, datadir=args.datadir, relion31=args.relion31, max_threads=args.max_threads, window_r=args.window_r)
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/dataset.py", line 108, in __init__
    particles = load_particles(mrcfile, False, datadir=datadir, relion31=relion31)
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/dataset.py", line 36, in load_particles
    particles, _ = mrc.parse_mrc(mrcs_txt_star, lazy=lazy)
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/mrc.py", line 145, in parse_mrc
    header = MRCHeader.parse(fname)
  File "/central/groups/voorheeslab/gpintont/conda-envs2/envs /cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.4-py3.7. egg/cryodrgn/mrc.py", line 55, in parse
    header = cls(cls.STRUCT.unpack(f.read(1024)))
struct.error: unpack requires a buffer of 1024 bytes

**Comment by zhonge** [comment]
Can you provide your downsample command?

Also, you'll want to run `cryodrgn train_vae` somewhere where there are GPUs available.
> 2022-01-31 16:33:13 Use cuda False
> 2022-01-31 16:33:13 WARNING: No GPUs detected

**Comment by zhonge** [comment]
Thanks for the additional details. I am not sure what the problem is from the error message -- it could be that you don't have sufficient memory to load the whole dataset. Can you verify that the `particles.200.mrcs` file is the expected size? Could you see if rerunning the command works with the `--lazy` flag?

I would also recommend training with downsampled images (`-D 128`) for initial testing with cryodrgn. The training time will be much faster. Here's the recommended protocol: https://www.notion.so/cryoDRGN-EMPIAR-10076-tutorial-c8728dcc88e744c8827447c3ff094d19#d5707f1475d74ed482a1322506def749

**Comment by gptomaleri** [comment]
I figure out that I made a mistake when I was generating the ctf.pkl and poses.pkl 

Now it is running just fine. -- Thanks!!! 

I was wondering if you had any suggestions for running cryoDRGN for membrane proteins. In one of the talks available online, you suggested particle subtraction... Any tips? 

Thanks.
