### ISSUE TITLE
Installation error during jupyter installation

### ISSUE THREAD

**Issue by olibclarke** [ml-struct-bio/cryodrgn#243]
Hi, I am trying to install cryodrgn on a new system, following the guide here:

https://www.notion.so/cryoDRGN-installation-with-anaconda-4cff0367d9b241bb8d902efe339d01e6#2ff3c5f9993247cfa908ec79728fd98d

When I get to the section involving jupyter installation, it fails with an error:

```
(cryodrgn) user@ubuntu:~$ jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
Traceback (most recent call last):
  File "/home/user/software/miniconda3/envs/cryodrgn/bin/jupyter-labextension", line 6, in <module>
    from jupyterlab.labextensions import main
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 14, in <module>
    from jupyterlab.coreconfig import CoreConfig
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyterlab/coreconfig.py", line 9, in <module>
    from .jlpmapp import HERE
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyterlab/jlpmapp.py", line 10, in <module>
    from jupyterlab_server.process import subprocess, which
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyterlab_server/__init__.py", line 5, in <module>
    from .app import LabServerApp
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyterlab_server/app.py", line 6, in <module>
    from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 12, in <module>
    from jupyter_server.serverapp import ServerApp
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 112, in <module>
    from jupyter_server.services.contents.filemanager import (
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyter_server/services/contents/filemanager.py", line 28, in <module>
    from .manager import AsyncContentsManager, ContentsManager
  File "/home/user/software/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/jupyter_server/services/contents/manager.py", line 11, in <module>
    from jupyter_core.utils import run_sync
ImportError: cannot import name 'run_sync' from 'jupyter_core.utils' (/home/user/.local/lib/python3.9/site-packages/jupyter_core/utils/__init__.py)
```

This is an Ubuntu 20.04 system.

Cheers
Oli

**Comment by Guillawme** [comment]
From my understanding, the accurate and current documentation is now at https://zhonge.github.io/cryodrgn and the content in Notion is out of sync with it (and likely out of date as well). Is that right?

**Comment by olibclarke** [comment]
Ok, so following those instructions I run into an error during installation of pytorch:

```
(cryodrgn) user@ubuntu:~/software$ conda install pytorch cudatoolkit=11.7 -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.7

Current channels:

  - https://conda.anaconda.org/pytorch/linux-64
  - https://conda.anaconda.org/pytorch/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

I can install it as `cudatoolkit` with unspecified version, but not with the version provided in the docs; Also it is stated in the docs to replace with the matching version to what we are using for `nvidia-smi`, but we are using 12.0 and that doesn't seem to exist

**Comment by olibclarke** [comment]
Ok got it installed and ran the quicktest, seems to run fine - one warning during the quicktest:

```
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
```

**Comment by Guillawme** [comment]
I don't think you need to worry about the CUDA version, as long as it is more recent than your Nvidia driver version. See the "compatibility" row of the table in the FAQ: https://docs.nvidia.com/deploy/cuda-compatibility/index.html#faq

I have had no problem using different versions of CUDA without upgrading the driver. `nvidia-smi` will always report the CUDA version that came out at the same time as the driver version, but this won't necessarily match the version that is actually in use on your system (you may even have different CUDA versions in different conda environments).
