### ISSUE TITLE
Assertion error following downsampling

### ISSUE THREAD

**Issue by kmradford** [ml-struct-bio/cryodrgn#295]
Hi there, 
This is awesome! I'm (more or less) following the tutorial in your paper, but I'm foolishly doing it on my own data. I chose to use a particle stack from a heterogeneous refinement job in cryoSPARC. 

**Files selected:** 

- parse_pose_csparc: J37_class_01_00182_particles.cs - this is the final particle stack from the refinement of class 01. I specified that it was from a heterogeneous refinement job. 
- parse_ctf_csparc: J37_passthrough_particles_class_1.cs - I went and checked the filename in cryoSPARC for the CTF from this job, and apparently this was it.
- downsample: J37_class_01_00182_volume.mrc - this already had a box size of 128, so nothing to downsample, but I did it anyway. 

When I got to step 5 (running backproject_voxel), it threw this error: 

```
[kradford@server protein_cryodrgn]$ cryodrgn backproject_voxel J37_01_particles.128.txt --uninvert-data --poses J37_01_poses.pkl --ctf J37_01_ctf.pkl -o J37_01_backproject.128.mrc
2023-07-20 23:49:48.662773     Namespace(particles='/data/work/kradford/data/protein_cryodrgn/J37_01_particles.128.txt', poses='/data/work/kradford/data/protein_cryodrgn/J37_01_poses.pkl', ctf='/data/work/kradford/data/protein_cryodrgn/J37_01_ctf.pkl', o='/data/work/kradford/data/protein_cryodrgn/J37_01_backproject.128.mrc', invert_data=False, datadir=None, ind=None, first=10000, preprocessed=False, tilt=None, tilt_deg=45, func=<function main at 0x7f5585a53dc0>)
2023-07-20 23:49:48.663049     Use cuda False
2023-07-20 23:49:48.663077     WARNING: No GPUs detected
2023-07-20 23:49:48.683572     Loaded 128 128x128 images
Traceback (most recent call last):
  File "/programs/x86_64-linux//cryodrgn/1.1.2/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/commands/backproject_voxel.py", line 147, in main
    posetracker = PoseTracker.load(args.poses, Nimg, D, None, args.ind, device=device)
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/pose.py", line 74, in load
    assert rots.shape == (
AssertionError: Input rotations have shape (172116, 3, 3) but expected (128,3,3)
```

I'm pretty sure that there's a header somewhere organized in a way it doesn't expect - the number it has pulled is the particle count, rather than the pixel count. Did I choose the wrong start files? Any idea how I can do this correctly? 

Thanks all, 
Bw, Kate

**Comment by zhonge** [comment]
Hi Kate, thank you for writing! I think you are downsampling and then running `cryodrgn backproject_voxel` on a volume instead of a stack of images. What was the command you provided `cryodrgn downsample`?  You should be able to provide `cryodrgn downsample` the `J37_class_01_00182_particles.cs` file with the appropriate `--datadir`.

**Comment by kmradford** [comment]
Ah! That would do it. I gave it this command: 

`
cryodrgn downsample J37_class_01_00182_volume.mrc -D 128 -o /data/work/kradford/data/protein_cryodrgn/J37_01_particles.128.mrcs --chunk 50000`

I was following the step in the paper that says: 

"Downsample the dataset to D = 128 px and D = 256 px, which we will use in the first and second training rounds, respectively. Here we split the particle stacks into 50,000 particle substacks with `--chunk` to decrease the memory footprint. These chunked .mrcs files are identified by an auto-generated `particles.[px].txt` file.

`
cryodrgn downsample 10076/data/L17Combine_weight_local.mrc -D 128 -o particles.128.mrcs --chunk 50000`"

I'll try running `cryodrgn downsample` on the .cs file and then run the `backproject_voxels` job and let you know what happens. 

Thank you so much!

**Comment by kmradford** [comment]
Okay, when I do that, I get the following error: 

```
[kradford@cemaster J37]$ cryodrgn downsample J37_class_01_00182_particles.cs -D 128 -o /data/work/kradford/data/RzAgo_cryodrgn/J37_particles_128_3.mrcs --chunk 50000
Traceback (most recent call last):
  File "/programs/x86_64-linux//cryodrgn/1.1.2/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/commands/downsample.py", line 77, in main
    old = dataset.load_particles(args.mrcs, lazy=lazy, datadir=args.datadir)
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/dataset.py", line 46, in load_particles
    particles = starfile.csparc_get_particles(mrcs_txt_star, datadir, lazy)
  File "/programs/x86_64-linux/cryodrgn/1.1.2/miniconda/lib/python3.9/site-packages/cryodrgn/starfile.py", line 168, in csparc_get_particles
    ind = metadata["blob/idx"]  # 0-based indexing
ValueError: no field of name blob/idx

```

I tried running the .mrc file again with the `--is-vol` tag to see if that helped, but I got the same error ultimately when backprojecting. 

It's also possible that this step is throwing cryodrgn off because the particles are already at D = 128 - could that be a problem? 

What do you think is up?

**Comment by zhonge** [comment]
It looks like there have been some updates in the format of the `.cs` file. We can look into that... As a workaround, I believe there is a downsample job in cryoSPARC that you could use instead.
