### ISSUE TITLE
AssertionError when filtering particles with write_star

### ISSUE THREAD

**Issue by Oanden** [ml-struct-bio/cryodrgn#311]
**Hello! I'm trying to create a .star file of my filtered particles for additional processing in Relion, by running the following command when in the Relion project directory (where the original particle set was processed):**
`cryodrgn_utils write_star Refine3D/job098/run_data.star --ind path-to-filtered-particles/filtered_particles.pkl -o path-to-filtered-particles/filtered_particles.star`

**But I get this error:**

Traceback (most recent call last):
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/starfile.py", line 166, in prefix_paths
    assert os.path.exists(path)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/bin/cryodrgn_utils", line 8, in <module>
    sys.exit(main())
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/utils_exec.py", line 65, in main
    args.func(args)
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands_utils/write_star.py", line 87, in main
    particles = starfile.get_particles(
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/starfile.py", line 146, in get_particles
    mrcs = prefix_paths(mrcs, datadir)
  File "/opt/cryoem/cryodrgn/2.2.0/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/starfile.py", line 170, in prefix_paths
    assert os.path.exists(path), f"{path} not found"
AssertionError: Refine3D/job098/Extract/job088/Movies/GridSquare_4269691/Data/FoilHole_4282318_Data_4273449_4273451_20210205_171513_fractions.mrcs not found

**So it looks like it is trying to find the Extract directory inside of the Refine3D job. Is this a bug or am I doing something wrong?**

**I also tried moving the original particles star file out to the project directory, but I still got the same error (where it instead said it could not find Extract/job088/Movies/etc.).**  

**I have tried it with cryoDRGN 2.2.0 and 2.3.0 and got the exact same error. I also tried with 3.0.0-beta and then just got the error (below) that it was unable to find the micrograph because it is looking for it in the wrong directory (ie. in the Refine3D job rather than the Extract job):**

Traceback (most recent call last):
  File "/opt/cryoem/cryodrgn/3.0.0-beta/bin/cryodrgn_utils", line 8, in <module>
    sys.exit(main())
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/utils_exec.py", line 65, in main
    args.func(args)
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/commands_utils/write_star.py", line 74, in main
    particles = ImageSource.from_file(args.particles, lazy=True)
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/source.py", line 58, in from_file
    return StarfileSource(
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/source.py", line 393, in __init__
    super().__init__(
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/source.py", line 332, in __init__
    D = MRCFileSource(self.df["__mrc_filepath"][0]).D
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/source.py", line 238, in __init__
    header = MRCHeader.parse(filepath)
  File "/opt/cryoem/cryodrgn/3.0.0-beta/lib/python3.10/site-packages/cryodrgn/mrc.py", line 104, in parse
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'path-to-relion-project-directory/Refine3D/job098/FoilHole_16812391_Data_16796105_16796107_20210317_184758_fractions.mrcs'

**Grateful for any advise as to what I might be doing wrong or suggestions to possible work arounds.**

**Comment by zhonge** [comment]
Hi, sorry to hear about the filtering / path issues and thanks for the detailed error messages.

* I think you probably want `cryodrgn_utils filter_star` to filter the rows of the existing run_data.star file, assuming that the star file corresponds to the same particle stack that you used in cryodrgn 
* I believe the errors above are because you need to provide `--datadir` to the `cryodrgn_utils write_star` command. You may also need the `--full-path` argument to `cryodrgn_utils write_star`

To filter an existing star file:
```
(cryodrgn) [Fri Oct 13 09:51 cryodrgn] cryodrgn_utils filter_star -h
usage: cryodrgn_utils filter_star [-h] --ind IND [-o O] input

Filter a .star file

positional arguments:
  input       Input .star file

options:
  -h, --help  show this help message and exit
  --ind IND   Array of selected indices (.pkl)
  -o O        Output .star file
  ```
  
  To write a new star file from .mrcs and ctf parameters:
  ```
  (cryodrgn2) [Fri Oct 13 09:51 cryodrgn] cryodrgn_utils write_star -h
usage: cryodrgn_utils write_star [-h] [--ctf CTF] [--poses POSES] [--ind IND] [--full-path] -o O particles

Create a Relion 3.0 star file from a particle stack and ctf parameters

positional arguments:
  particles      Input particles (.mrcs, .txt, .star)

options:
  -h, --help     show this help message and exit
  --ctf CTF      Input ctf.pkl
  --poses POSES  Optionally include pose.pkl
  --ind IND      Optionally filter by array of selected indices (.pkl)
  --full-path    Write the full path to particles (default: relative paths)
  -o O           Output .star file
  ```
