### ISSUE TITLE
ver 3.0.0. install error

### ISSUE THREAD

**Issue by jychoi0616** [ml-struct-bio/cryodrgn#314]
**Describe the bug**
v.3.0.0. install using source code gives error with following error message. (installation using git clone worked well for ver 2.3.0): 
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.

**To Reproduce**
What is the command you used?

pip install .

**Expected behavior**

**Additional context**

I copied full error message below in case this helps:

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing /data/cryodrgn-3.0.0-beta
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Traceback (most recent call last):
        File "/data/miniconda3/envs/cryodrgn_3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/data/miniconda3/envs/cryodrgn_3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/data/miniconda3/envs/cryodrgn_3/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 680, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 121, in infer_version
          _assign_version(dist, config)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py", line 56, in _assign_version
          _version_missing(config)
        File "/tmp/pip-build-env-02yx7jkw/overlay/lib/python3.9/site-packages/setuptools_scm/_get_version_impl.py", line 112, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /data/cryodrgn-3.0.0-beta.
      
      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
      
      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Guillawme** [comment]
Hello,

> What is the command you used?
> 
> pip install .

This means you installed from the content of the repository. Do you know which commit you installed? If it is not one listed as a [release](https://github.com/ml-struct-bio/cryodrgn/releases), it is not guaranteed to work.

You should install with the command `pip install cryodrgn` instead (and preferably run in a fresh conda environment), which will fetch a released version. You can even choose which version, as long as it was uploaded to the [Python package index (PyPI)](https://pypi.org/project/cryodrgn/). So you want version 3, but it looks like 2.3.0 is the most recent stable release, and there must be good reasons why version 3 is still marked as beta here and not released on PyPI.

**Comment by jychoi0616** [comment]
Thank you for your reply!
I used [Version 3.0.0-beta](https://github.com/ml-struct-bio/cryodrgn/releases/tag/3.0.0-beta), and used pip install . command following this installation instruction described in https://ez-lab.gitbook.io/cryodrgn/installation:

"
Alternatively, if you prefer not to use git, you can directly download a ZIP file of the latest release from https://github.com/zhonge/cryodrgn/releases
For example, if the latest release is cryodrgn-2.3.0.zip:
(cryodrgn) $ unzip cryodrgn-2.3.0.zip
(cryodrgn) $ cd cryodrgn-2.3.0
(cryodrgn) $ pip install .
"

which I changed from 2.3.0. to 3.0.0

**Comment by jychoi0616** [comment]
Hi,


Below are the contents:


LICENSE.txt  README.md         cryodrgn               docs            sweep.sh  tests  versions.txt

MANIFEST.in  analysis_scripts  cython_constraint.txt  pyproject.toml  testing   utils



Best wishes,

Joy



On 23 Oct 2023, at 20:49, Michal Grzadkowski ***@***.***> wrote:



Hi, can you show us the contents of the directory you are installing from? e.g. run ls or tree after you cd into the cryodrgn directory you are running the pip install . command from.

**Comment by michal-g** [comment]
What `git clone` command did you use when getting the repo? Can you try again using `git clone git@github.com:ml-struct-bio/cryodrgn.git`?

**Comment by jychoi0616** [comment]
Hi Michael,

It seems that I don’t have an access to the git clone directory.
I’ve got following message when I prompted your suggestion:

      Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
      Permission denied (publickey).
      fatal: Could not read from remote repository.
      
      Please make sure you have the correct access rights
      and the repository exists.

Also, initially i couldn’t git clone to install the 3.0.0. beta version, because it seemed the existing git clone link was for the version of 2.3.0 (btw I have successfully installed this using git clone), so I downloaded source code from the release tab, and did unzip as described in the installation page (https://ez-lab.gitbook.io/cryodrgn/installation)

**Comment by jychoi0616** [comment]
Hi, 
I copied what you wrote in the beginning (git clone git@github.com:ml-struct-bio/cryodrgn.git) which gave the earlier error.
And now if I do the https now, I got these error:

    fatal: destination path 'cryodrgn' already exists and is not an empty directory.

and if I do git pull 

      fatal: Not a git repository (or any parent up to mount point /data)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
      
My question is does the git clone contain information of ver 3.0.0-beta???
