### ISSUE TITLE
Cryodrgn analyze, SVD did not converge

### ISSUE THREAD

**Issue by lainahall** [ml-struct-bio/cryodrgn#334]
I am running into an issue when I try to  use cryodrgn analyze: 
```
`/cryodragon$ cryodrgn analyze test128flip/00_vae128 49 --flip --Apix 3.18
(INFO) (analyze.py) (10-Jan-24 10:45:41) Saving results to /home/laina/cryodragon/test128flip/00_vae128/analyze.49
(INFO) (analyze.py) (10-Jan-24 10:45:41) Performing principal component analysis...
Traceback (most recent call last):
  File "/home/laina/.local/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/laina/.local/lib/python3.7/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/laina/.local/lib/python3.7/site-packages/cryodrgn/commands/analyze.py", line 391, in main
    num_ksamples=args.ksample,
  File "/home/laina/.local/lib/python3.7/site-packages/cryodrgn/commands/analyze.py", line 108, in analyze_zN
    pc, pca = analysis.run_pca(z)
  File "/home/laina/.local/lib/python3.7/site-packages/cryodrgn/analysis.py", line 41, in run_pca
    pca.fit(z)
  File "/usr/local/EMAN_2.91/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 352, in fit
    self._fit(X)
  File "/usr/local/EMAN_2.91/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 423, in _fit
    return self._fit_full(X, n_components)
  File "/usr/local/EMAN_2.91/lib/python3.7/site-packages/sklearn/decomposition/_pca.py", line 454, in _fit_full
    U, S, Vt = linalg.svd(X, full_matrices=False)
  File "/usr/local/EMAN_2.91/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 129, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.LinAlgError: SVD did not converge`
```

**Comment by lainahall** [comment]
I added --pc 3 and this helped

**Comment by lainahall** [comment]
It does work occasionally and I get this output:
