### ISSUE TITLE
cryodrgn analyze

### ISSUE THREAD

**Issue by lainahall** [ml-struct-bio/cryodrgn#336]
**Describe the bug**
An issue within UMAP of cryodrgn Analyze

**To Reproduce**
cryodrgn analyze
**Expected behavior**
I can get by this by inputting --skip-umap but otherwise my analyze job stops before creating the jupyter notebook

**Additional context**
```
`(INFO) (analyze.py) (16-Jan-24 09:08:12) Running UMAP...
/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12050. The TBB threading layer is disabled.
  warnings.warn(problem)
(INFO) (analyze.py) (16-Jan-24 09:08:43) Generating plots...
/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/seaborn/_decorators.py:36: FutureWarning: Pass the following variables as keyword args: x, y. From version 0.12, the only valid positional argument will be `data`, and passing other arguments without an explicit keyword will result in an error or misinterpretation.
  warnings.warn(
Traceback (most recent call last):
  File "/home/exx/.conda/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/commands/analyze.py", line 385, in main
    analyze_zN(
  File "/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/commands/analyze.py", line 250, in analyze_zN
    analysis.scatter_color(
  File "/home/exx/.conda/envs/cryodrgn/lib/python3.10/site-packages/cryodrgn/analysis.py", line 337, in scatter_color
    cbar.draw_all()
AttributeError: 'Colorbar' object has no attribute 'draw_all'. Did you mean: '_draw_all'?`
```

**Comment by michal-g** [comment]
Can you check what version of `matplotlib` you have installed? As per past issue #312 this is likely due to having v3.7 or v3.8 — while we are still planning to replace the deprecated `draw_all` calls in the code, for now the recommended fix is to downgrade to v3.6.
