### ISSUE TITLE
RuntimeError: The size of tensor a (16641) must match the size of tensor b (129) at non-singleton dimension 2

### ISSUE THREAD

**Issue by CTosXY** [ml-struct-bio/cryodrgn#351]
Hi,Zhong! I have tested pose/CTF parameters parsing by the voxel-based backprojection script, and the output structure resembles the structure from the consensus reconstruction.
However, the training process report such an error, the following is the log. (the extracted particle were from different batchs micrographs data, whether it is matter?)
We are looking forword your reply.

[runlog.txt](https://github.com/ml-struct-bio/cryodrgn/files/14416940/runlog.txt)
/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1699449181081/work/aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main())
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/__main__.py", line 72, in main
    args.func(args)
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/train_vae.py", line 910, in main
    loss, gen_loss, kld = train_batch(
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/train_vae.py", line 360, in train_batch
    y = preprocess_input(y, lattice, trans)
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/commands/train_vae.py", line 405, in preprocess_input
    y = lattice.translate_ht(y.view(B, -1), trans.unsqueeze(1)).view(B, D, D)
  File "/opt/ohpc/pub/apps/miniconda3/envs/cryodrgn/lib/python3.9/site-packages/cryodrgn/lattice.py", line 163, in translate_ht
    return c * img + s * img[:, :, torch.arange(len(coords) - 1, -1, -1)]
RuntimeError: The size of tensor a (16641) must match the size of tensor b (129) at non-singleton dimension 2

**Comment by RajShekhorRoy** [comment]
Previously, I faced this issue too and it seemed that using a batch size of 28 or 128 solved it for me.

Regards,
Raj

**Comment by CTosXY** [comment]
> Previously, I faced this issue too and it seemed that using a batch size of 28 or 128 solved it for me.
> 
> Regards, Raj

Thanks a lot! It seems work!
