### ISSUE TITLE
CUDA error in add_for_corner when running backproject_voxel

### ISSUE THREAD

**Issue by michal-g** [ml-struct-bio/cryodrgn#380]
**Describe the bug**
For some inputs, backprojection will run for a number of iterations (in this case, about 265k) but then fail at a particular image with a cryptic CUDA error:
```
/home/conda/feedstock_root/build_artifacts/pytorch-recipe_1650965732461/work/aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/scratch/gpfs/mg2332/conda_envs/cryodrgn-3.3.3_dev/bin/cryodrgn", line 8, in <module>
    sys.exit(main_commands())
  File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/command_line.py", line 68, in main_commands
    _get_commands(
  File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/command_line.py", line 63, in _get_commands
    args.func(args)
  File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/commands/backproject_voxel.py", line 288, in main
    add_slice(volume_full, counts_full, ff_coord, ff, D, ctf_mul)
  File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/commands/backproject_voxel.py", line 146, in add_slice
    add_for_corner(xf, yf, zc)
  File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/commands/backproject_voxel.py", line 140, in add_for_corner
    volume[(zi + d2, yi + d2, xi + d2)] += w * ff * ctf_mul
RuntimeError: CUDA error: device-side assert triggered
```

**To Reproduce**
A standard backprojection reconstruction with a `.txt` particle stack:
```
cryodrgn backproject_voxel stack.128.txt --lazy --ctf ctf.pkl --poses poses.pkl -o vol.mrc
```
Inputs were double-checked with no obvious issues!

**Expected behavior**
The `backproject_voxel` command should run to completion for all valid inputs.

**Comment by michal-g** [comment]
After some digging into this we found that the cause was a numerical rounding issue when calculating Fourier-transformed co-ordinates `ff_coord = lattice.coords[mask] @ r` in `backproject_voxel`:

```
File "/home/mg2332/dev/cryodrgn_beta/cryodrgn/commands/backproject_voxel.py", line 140, in add_for_corner
    volume[(zi + d2, yi + d2, xi + d2)] += w * ff * ctf_mul
IndexError: index 129 is out of bounds for dimension 0 with size 129
```

The values of `ff_coord`, which are mathematically bound by `[-D/2, D/2]` for valid rotation matrices `r`, can slightly violate these bounds if `r` is not quite a valid rotation matrix due to a lack of numerical precision. This can occur e.g. when the rotation matrices are stored as values rounded to six decimal places, resulting in matrices with determinants like `0.9999994`, which are thus valid rotation matrices modulo the rounding error. In turn, this produces a problem when the "corners" of `ff_coord` are used in `backproject_voxel.add_slice()`:
```
d2 = int(D / 2)
ff_coord = ff_coord.transpose(0, 1)
xf, yf, zf = ff_coord.floor().long()
xc, yc, zc = ff_coord.ceil().long()

def add_for_corner(xi, yi, zi):
    dist = torch.stack([xi, yi, zi]).float() - ff_coord
    w = 1 - dist.pow(2).sum(0).pow(0.5)
    w[w < 0] = 0
    volume[(zi + d2, yi + d2, xi + d2)] += w * ff * ctf_mul
    counts[(zi + d2, yi + d2, xi + d2)] += w * ctf_mul**2

add_for_corner(xf, yf, zf)
add_for_corner(xc, yf, zf)
```
where the matrix `volume` has dimensions of size `D+1`, and the index `zi + d2` can take on values greater than `D` if `zi > D/2`!

To solve this (in ec16068) we simply truncate the values of `ff_coord` after they are calculated to smooth out any numerical issues:
```
d2 = int(D / 2)
ff_coord = ff_coord.transpose(0, 1).clip(-d2, d2)
xf, yf, zf = ff_coord.floor().long()
xc, yc, zc = ff_coord.ceil().long()
```
