### ISSUE TITLE
error running cryodrgn downsample

### ISSUE THREAD

**Issue by wsalmen2** [ml-struct-bio/cryodrgn#408]
I am running into an error using cryodrgn downsample version 3.4.0 

command:
cryodrgn downsample J986_particles_exported.cs -D 256 -o new_particles_256.mrcs

Output:
Traceback (most recent call last):
  File "/programs/x86_64-linux//cryodrgn/3.3.3/cryodrgn/bin/cryodrgn", line 8, in <module>
    sys.exit(main_commands())
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgn/command_line.py", line 81, in main_commands
    _get_commands(
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgn/command_line.py", line 76, in _get_commands
    args.func(args)
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgn/commands/downsample.py", line 206, in main
    mkbasedir(args.outfile)
  File "/Users/salmen/.local/lib/python3.9/site-packages/cryodrgn/commands/downsample.py", line 109, in mkbasedir
    os.makedirs(os.path.dirname(out))
  File "/programs/x86_64-linux/cryodrgn/3.3.3/miniconda/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''

I have run this command with and without a --datadir path and it returns the same error. This command previously worked on the exact same files using version 3.3.3. Not sure if I am doing something wrong, or if this is from the new update.

-Wil

**Comment by michal-g** [comment]
Hi Wil, thanks for raising this, we just fixed this issue in [v3.4.1](https://github.com/ml-struct-bio/cryodrgn/releases/tag/3.4.1) released yesterday! Reinstalling with `pip install cryodrgn` or `pip install 'cryodrgn==3.4.1'` should get `downsample` back to the expected behaviour, as should specifying an absolute path or one with a leading directory in v3.4.0 (e.g. `/scratch/my_datasets/new_particles_256.mrcs` or `my_data_dir/new_particles_256.mrcs`).

-Mike

**Comment by wsalmen2** [comment]
Great, thank you!

-Wil
