### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by sunchang1990** [ml-struct-bio/cryodrgn#93]
Traceback (most recent call last):
  File "/goliath/sw/conda4.10/envs/cryodrgn/bin/cryodrgn", line 33, in <module>
    sys.exit(load_entry_point('cryodrgn==0.3.3b0', 'console_scripts', 'cryodrgn')())
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.3b0-py3.7.egg/cryodrgn/__main__.py", line 54, in main
    args.func(args)
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.3b0-py3.7.egg/cryodrgn/commands/train_vae.py", line 319, in main
    data = dataset.MRCData(args.particles, norm=args.norm, invert_data=args.invert_data, ind=ind, keepreal=args.use_real, window=args.window, datadir=args.datadir, relion31=args.relion31, max_threads=args.max_threads, window_r=args.window_r)
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/site-packages/cryodrgn-0.3.3b0-py3.7.egg/cryodrgn/dataset.py", line 124, in __init__
    with Pool(max_threads) as p:
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/goliath/sw/conda4.10/envs/cryodrgn/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

I was trying to use cryodrgn to train a 176GB dataset in a workstation with 1.5TB memory. At the end of the memory allocation, when the free command showed about 176 GB as buffer/cache, cryodrgn gave the above error. Any idea why this is happening? Thanks!

**Comment by sunchang1990** [comment]
cryodrgn version: 7a79f1cc8e62e26df9bdf2d30d068a6ad474b901
command used: cryodrgn train_vae /goliath/processing/Gouaux/sunch/20210618/P180/J404/cryosparc_P180_J404_003_particles.cs --poses pose.pkl --ctf ctf.pkl -o 00_vae120_z8 --zdim 8 -n 50 --datadir /goliath/processing/Gouaux/sunch/20210618/P180/J396/downsample

**Comment by Guillawme** [comment]
Do you also get this error with the `--lazy` option?

**Comment by sunchang1990** [comment]
Yes, --lazy option works, but the performance might not be optimal. With 3.2 M 120x120 particles, each iteration took about 2 hours with SSD and 6 GPUs. A 50-iteration training is simply taking too long. I am curious to see the result when it finishes later this week.

**Comment by Guillawme** [comment]
With this many particles it is going to take a long time no matter what.

**Comment by zhonge** [comment]
How much memory do you have on your machine?

I think the easiest thing just to get things running is to try it out on a subset of the dataset -- maybe 400k particles? I just committed a helper script that I sometimes use to get a random selection of particles. The usage is:

```
$ python utils/make_train_test.py [Nparticles] -n 400000 -o selection
```

where you would replace `Nparticles` with the number of particles in your dataset. There will be an output file `selection.train.pkl` saved that you can then provide to `cryodrgn train_vae` with the `--ind` flag.

Another option is to try out the `cryodrgn preprocess` [workflow](https://www.notion.so/cryodrgn-preprocess-d84a9d9df8634a6a8bfd32d6b5e737ef) which is less memory intensive.

If that doesn't work, you could try training with the `--lazy` flag, although I only recommend that if you have the particles on an SSD hard drive. Otherwise the disk access is much too slow. You probably don't need 50 epochs (maybe only 20?) and you can also check the intermediate results with `cryodrgn analyze` during training.

**Comment by michal-g** [comment]
There is still work to be done on optimizing the runtime and memory efficiency of cryoDRGN, but lazy loading of datasets is for now our best tool for avoiding excessive memory use (at the expense of runtime).
